### ISSUE TITLE
Refuses to raise certain applications

### ISSUE THREAD

**Issue by codesections** [Soft/run-or-raise#1]
Thanks very much for building this—I can see it being very useful/fitting in well with my workflow. 

In fact, I was especially looking forward to using `run-or-raise` with a particular application: the [Zoom](https://zoom.us/) video-chat client, which I frequently lose track of across my different desktops.

Unfortunately, run-or-raise doesn't initially seem to work with Zoom, even though it works well with other apps.  The "run" portion works fine, but the "raise" does not have any effect.  I can tell that I'm correctly targeting the Zoom window because the "run" half of the command does *not* run (the way it would if I were not targeting a valid window).  But the Zoom window isn't focused or raised in any way.

Any idea what the issue could be?

I'm running the linux version of the Zoom client on Arch Linux in case that is relevant (though, like I said, I'm able to use run-or-raise with other clients without any trouble).

Thanks again for this!

**Comment by Soft** [comment]
Hmm, I haven't seen this type of issues before. Unfortunatelly, I do not have access to this particular application to reproduce the issue myself.

My guess is that maybe you are still matching a wrong window in some way. Could it be possible that Zoom actually creates multiple windows (some of which could be somehow special and hidden) and you are accidentally trying to focus one of these hidden windows. Have you tried focusing the window using some alternative tools doing similar things? Does something [wmctrl](http://tripie.sweb.cz/utils/wmctrl/) work? Have you tried inspecing the properites of the window you want to focus using something like `xprop`?

**Comment by codesections** [comment]
You may well be correct about the multiple hidden windows—Zoom does create multiple windows for different video sessions.  I'll look into that and report back.

(The Zoom client is free to download on every platform, in case you *want* to try to reproduce the issue.  But I think you've given me enough to go on for now—thanks!)

**Comment by codesections** [comment]
You were correct: I was matching a hidden window that started with "Zoom".  When I made my selector more specific to the visible window, that resolved the issue.  (Specifically `name ~ "Zoom.*"` wouldn't work but `name ~ "Zoom.*Pro.*"` did.)

Thanks!
