### ISSUE TITLE
Fails to build on Fedora 36

### ISSUE THREAD

**Issue by absenth** [Soft/run-or-raise#4]
When trying to build Run or Raise with cargo, the build always fails as follows.  I am running Rust version 1.61.0 on Fedora 36.

` $ rustc --version
rustc 1.61.0 (Fedora 1.61.0-2.fc36)
`
`error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/cargo-installwdRHpE/release/deps/run_or_raise-3058fc70b4164559.run_or_raise.538db077-cgu.3.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installwdRHpE/release/deps" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-77561ea614728171.rlib" "-Wl,-Bdynamic" "-lxcb" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installwdRHpE/release/deps/run_or_raise-3058fc70b4164559" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lxcb
          collect2: error: ld returned 1 exit status
          

error: could not compile `run-or-raise` due to previous error
error: failed to compile `run-or-raise v0.3.4 (https://github.com/Soft/run-or-raise.git#64b34c5e)`, intermediate artifacts can be found at `/tmp/cargo-installwdRHpE`
`

**Comment by Soft** [comment]
I think you might be missing some of the dependencies. Installing libxcb-devel and libxcb packages might solve the problem.

**Comment by absenth** [comment]
> I think you might be missing some of the dependencies. Installing libxcb-devel and libxcb packages might solve the problem.

you're totally right.  I had the package, but not the `-devel` package installed.  Sorry for the noise, and thank you for the quick reply.
